[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/fpl-data"
  to = "/.netlify/functions/fpl-data"
  status = 200

[[redirects]]
  from = "/api/fpl-advice"
  to = "/.netlify/functions/fpl-advice"
  status = 200

[[redirects]]
  from = "/api/visit"
  to = "/.netlify/functions/visit"
  status = 200

[[redirects]]
  from = "/api/guestbook*"
  to = "/.netlify/functions/guestbook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
